### ISSUE TITLE
Create Model for LogSection

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#19]
When a user creates a MoneyLog in the spender app they have an option to split the budget into even sections so a `seven-day` MoneyLog split daily will have seven LogSections. A `month-long` split daily will have a LogSection for each day of the month. 
A LogSection will have the following fields 
- name: name of the log section is any otherwise the dates are used 
- money_log_id: id of the money log this section belongs to 
- duration: this is the duration of this section at the moment this is the duration of the budget divided by the number of sections
- section_position: the overall position of the section in the this budgets LogSections 
We need a model that can 
- [ ] Create a LogSection 
- [ ] Update  LogSection's Name
- [ ] Update a LogSection's Location

**Comment by zacck-zz** [comment]
# Notes 
Since  we are presuming a user to be in the planning stage of their MoneyLog we will need to follow a process

- [ ] Ensure that the MoneyLog in question has a `start_date` and an `end_date`
- [ ] Allow an Owner to enter an integer number of sections for a MoneyLog at which point we will calculate the length of time between the `start_date` and `end_date`
- [ ] Divide the `length` above by the number of sections and we have the `duration` for a section

At which point we have all the details we need generate sections for a budget using a default name 
`Section #{Number}`
